### ISSUE TITLE
would love to see an xplat "hello world" background task usage example

### ISSUE THREAD

**Issue by csells** [d-markey/squadron#1]
I'm interested in seeing the simplest possible usage of squadron, e.g. what's the code needed to calculate 10K digits of pi (or whatever)? how do I write that in a cross-platform way across mobile, desktop and web?

**Comment by d-markey** [comment]
Closing this issue, but don't hesitate to follow up should you have any comments!

**Comment by d-markey** [comment]
For anyone interested -- I've posted the sample on https://github.com/d-markey/squadron_sample and upgraded it to Squadron 3.1 including supports for task cancellation.

**Comment by csells** [comment]
nice!
