### ISSUE TITLE
would love the ability to pause and resume workers or worker pool.

### ISSUE THREAD

**Issue by cal-g** [d-markey/squadron#11]
Hello, it would be interesting to see if the package can be enhanced to allow for pausing and resuming workers or worker pools similarly to how dart `Isolate` can be paused and resumed.

**Comment by d-markey** [comment]
Hello @cal-g, unfortunately Web workers do not have this capacity, so there is no way to implement such a mechanism while keeping the cross-platform approach Squadron provides. So no, this can't and won't be implemented in Squadron.

I believe it would still be possible to implement that on top of Squadron, but the workers will have to collaborate in a way or another, and would be responsible to check for paused status as part of their normal workload.

I did a little bit of research and maybe https://stackoverflow.com/questions/57701464/is-it-possible-to-pause-resume-a-web-worker-externally will give you some hints?
