### ISSUE TITLE
Fix the dart to js parser code on the readme.md

### ISSUE THREAD

**Issue by reiko-dev** [d-markey/squadron#12]
On the section _**Releasing Your App**_ on the README.md file, the command to parse a dart file to Javascript is not accurate.
It shows:
`dart compile js -o lib/src/browser/service_worker.dart web/service_worker.dart.js`

But it should be like this:
`dart compile js lib/src/browser/service_worker.dart -o web/service_worker.dart.js`

The _-o_ indicates the path to the compiled js file, right?

Edit: I just saw that i'm in the samples repo, but the issue is still valid, not for this repo, but for the package one.

**Comment by d-markey** [comment]
Hi, that's right! Correction in progress, thanks
