### ISSUE TITLE
Shorten log message with settings

### ISSUE THREAD

**Issue by VladimirCores** [d-markey/squadron#16]
Could you please add a property that will disable time and frame information in the logs? Thanks.

![image](https://user-images.githubusercontent.com/442111/219867008-3f1d8a66-18cb-421a-8787-e4b98f3c413b.png)

**Comment by d-markey** [comment]
Hello,

I've taken a different approach to avoid adding new parameters to Squadron and decided to split the code between message formatting and message emitting in the base logger (default formatting simply calls `message.ToString()`). You can then implement your own logger on top of `BaseSquadronLogger` and avoid having the header in the log messages. E.g.:

```dart
class MySquadronLogger extends BaseSquadronLogger {
  /// Log to console
  @override
  void log(String message) => print(message);
}
```

**Comment by d-markey** [comment]
Closing this, please let me know if you need further help.

**Comment by VladimirCores** [comment]
Smart suggestion, thank you @d-markey ; )
