### ISSUE TITLE
v4.3.7 depends on meta: ^1.9.1 which is incompatible with fluter_test from Flutter 3.7.12

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron#18]
Hey! 👋

I love this package, however, due to the latest version v4.3.7 depending on `meta: ^1.9.1` I can't use it with Flutter 3.7.12

When trying to upgrade I get an error:
```
Because every version of flutter_test from sdk depends on meta 1.8.0 and squadron >=4.3.7 depends on meta ^1.9.1, flutter_test from sdk is incompatible with squadron >=4.3.7.
So, because test_app depends on both squadron ^4.3.7 and flutter_test from sdk, version solving failed.
```

Is there any specific reason you bumped the requirement to `meta: ^1.9.1`? I've seen that in v4.3.6 https://github.com/d-markey/squadron/commit/4123d9cee301805cbe431f4dd14d1d2ef816e50e you downgraded it back to `meta: ^1.8.0`

**Comment by d-markey** [comment]
Yup sorry, there was no reason apart from keeping up to date with latest dependencies. Downgrading back to 1.8.
