### ISSUE TITLE
http constraint too high

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron#23]
Hey,

I think that the `http: ^1.0.0` constraint is too draconian as a lot of packages still haven't adopted `1.0.0`.

I would sugges a more flexible approach like

```yaml
http: ">=0.13.6 <2.0.0"
```

**Comment by d-markey** [comment]
It's a dev dependency, so it shouldn't cause any trouble as they are ignored (https://dart.dev/tools/pub/dependencies#dev-dependencies).
