### ISSUE TITLE
WorkerException: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'SendPort?'

### ISSUE THREAD

**Issue by SwissCheese5** [d-markey/squadron#3]

**Comment by d-markey** [comment]
Transferred the issue to [Squadron](https://github.com/d-markey/squadron) as it really belons there

**Comment by d-markey** [comment]
Version 3.2 has been published to pub.dev!
You should be able to upgrade and remove the workaround try/catch from your `solver_worker.dart` file.
