### ISSUE TITLE
Expected a value of type 'Map<String, Object?>' but got one of type 'LinkedMap<dynamic, dynamic>'

### ISSUE THREAD

**Issue by sabin26** [d-markey/squadron#30]
I am returning this model class from squadron worker. Why is it that **this works on isolates but not on web workers** ? I do not see any data type that should not be transferred from web worker but still I am getting an exception. There are `fromJson` and `toJson` methods that work on Dart VM but not on web.

```dart
class HttpResponse extends Response {
  factory HttpResponse.fromJson(final Map<String, Object?> json) {
    return HttpResponse._bytes(
      json['bodyBytes']! as List<int>,
      json['statusCode']! as int,
      headers: json['headers']! as Map<String, String>,
      isRedirect: json['isRedirect']! as bool,
      persistentConnection: json['persistentConnection']! as bool,
      reasonPhrase: json['reasonPhrase'] as String?,
    );
  }
  HttpResponse._bytes(super.bodyBytes, super.statusCode,
      {super.headers,
      super.isRedirect,
      super.persistentConnection,
      super.reasonPhrase})
      : super.bytes();

  factory HttpResponse.fromResponse(final Response response) {
    return HttpResponse._bytes(
      response.bodyBytes,
      response.statusCode,
      headers: response.headers,
      isRedirect: response.isRedirect,
      persistentConnection: response.persistentConnection,
      reasonPhrase: response.reasonPhrase,
    );
  }

  Map<String, Object?> toJson() => {
        'bodyBytes': bodyBytes,
        'statusCode': statusCode,
        'headers': headers,
        'isRedirect': isRedirect,
        'persistentConnection': persistentConnection,
        'reasonPhrase': reasonPhrase,
      };
}
```

Here is the exception (Screenshot):

![image](https://github.com/d-markey/squadron/assets/61322712/ebc20ca2-c96a-43f4-af8d-3e40f2860be4)

**Comment by d-markey** [comment]
That's because JavaScript knows nothing about Dart strong types and generics, so any `List<T>` and `Map<K,V>` crossing the Web worker boundary becomes a plain `List<dynamic>` and `Map, dynamic, dynamic>` on the receiving end.

Try changing `factory HttpResponse.fromJson(final Map<String, Object?> json)` to `factory HttpResponse.fromJson(final Map json)` and you should be OK.

But then, it will probably choke on `as List<int>` and `as Map<String, dynamic>`. To fix that and regain strong types, you can write this instead:

```dart
json['bodyBytes']!.cast<int>(),
...
headers: json['headers']!.cast<String, String>()
...
```

**Comment by sabin26** [comment]
Thank you so much. It worked. It did not choke on List<int> but only on Map.
