### ISSUE TITLE
Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' 

### ISSUE THREAD

**Issue by menghuymjq** [d-markey/squadron#32]
When i use squadron to chunk file for upload using dio package, i want to return progress update on file upload to display on UI. but always throw that error on pool.start(). Is there way around to solve this problem?

**Comment by d-markey** [comment]
Hello, I need more details before I can answer this. Are you running on Web? How do you start the worker, more specifically, what arguments are you passing to initialize your service?Not all objects can be passed to workers and it seems you're passing something unsendable.Le 9 oct. 2023 06:51, trymenghuy mjq ***@***.***> a écrit :
When i use squadron to chunk file for upload using dio package, i want to return progress update on file upload to display on UI. but always throw that error on pool.start(). Is there way around to solve this problem?

**Comment by d-markey** [comment]
Hmm according to the error message that's a problem with Isolates so not Web. Please provide more code.

**Comment by d-markey** [comment]
Closing this as no more feedback was provided in two months.
