### ISSUE TITLE
flutter_service_worker.js - does it work together

### ISSUE THREAD

**Issue by makinghappen** [d-markey/squadron#41]
HI!

Does service_worker integrate with flutter_service_worker.js ? There cannot be two service workers, so to implement my own, I came across your package

In readme it is mentioned that:
```
To release the Browser version, the worker code must first be compiled to JavaScript:

dart compile js lib/src/browser/service_worker.dart -o web/service_worker.dart.js

Flutter's Web runtime includes a service worker called flutter_service_worker.js: make sure you use a different name for your workers to avoid any conflict! After compiling your worker scripts, you can build your app using:

flutter build web
```

But how then two service workers are to be included into index.html? Is there a working example for web?

**Comment by makinghappen** [comment]
lol, scam @Dominic54321

**Comment by d-markey** [comment]
Squadron is not about service workers and PWA, it's about Web workers, so yes, it works with `flutter_service_worker.js`.

**Comment by d-markey** [comment]
Working example for Web, see https://github.com/d-markey/flutter_mandel_squadron.

Also https://github.com/d-markey/squadron_sample but have a look at older versions then. Latest commits are works in progress.
