### ISSUE TITLE
Error: Type 'Releasable' not found

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron#42]
Hey :)

I recently upgraded from `v5.1.6` to `v6.0.2` and got this error when trying to compile my Flutter app with the generated code

```
Could not build the precompiled application for the device.
Error (Xcode): lib/src/core/api/data/service/json_service.worker.g.dart:47:35: Error: Type 'Releasable' not found.
```

Looks like one has to explicitly add
```dart
import 'package:using/using.dart';
```
to a service class.

**Comment by techouse** [comment]
The same goes for
```dart
import 'package:cancelation_token/cancelation_token.dart';
import 'package:logger/logger.dart';
```

**Comment by d-markey** [comment]
This should only be necessary if you asked squadron_builder to generate finalizable workers (see `with_finalizers` option in your build.yaml file).

In that case, the generated code relies on types from these packages (+ `dart:async` for `FutureOr`).

**Comment by d-markey** [comment]
Hello @techouse, did you manage to have generate the code for your workers?

**Comment by techouse** [comment]
Yes, I worked around the issue by simply importing the libraries in the service, i.e.
```dart
// ignore_for_file: depend_on_referenced_packages
import 'dart:async';
import 'dart:convert' show jsonDecode;

import 'package:cancelation_token/cancelation_token.dart';
import 'package:logger/logger.dart';
import 'package:squadron/squadron.dart';
import 'package:using/using.dart';

import 'json_service.activator.g.dart';

part 'json_service.worker.g.dart';

@SquadronService(targetPlatform: TargetPlatform.vm)
base class JsonService {
  @SquadronMethod()
  FutureOr<dynamic> decode(String source) => jsonDecode(source);
}
```
