### ISSUE TITLE
Optionaly use marshalers for web platforms only

### ISSUE THREAD

**Issue by tlvenn** [d-markey/squadron#43]
I was wondering if it would be possible to have some marshalers be used only in the context of the web and not with native code ?

I have a relatively complex object that I need to marshal for the web and would rather let the dart vm do it itself on native platforms which is probably less expensive than my own serialization / deserialization.

**Comment by d-markey** [comment]
You can, via conditionnal import: in the Web implementation, use your current marshaler deriving from SquadronMarshaler<T,V>; in the VM implementation, use the IdentityMarshaler<T> which simply casts the data in and out.

**Comment by tlvenn** [comment]
Ha why didn't I think about that...
It might be something worth mentioning in the doc / wiki.

Merci !

**Comment by d-markey** [comment]
I've updated the readme file. Need more time to work on the wiki!

**Comment by AlexDochioiu** [comment]
@d-markey I have been doing this for a while but it's always been a bit annoying. I think this should be default behaviour unless user explicitly wants to use marshaler on VM as well.

Also, I see `IdentityMarshaler` is now final since v6. Can this be reverted please?

**Comment by d-markey** [comment]
Hello @AlexDochioiu,

`IdentityMarshaler` is not intended to be subclassed as the implementation will always be the same. Also, it's a constant class so the idea is to actually instantiate the marshaler in a top-level constant and use the constant for annotations, eg:

```dart
// create the marshaler, if Web is required you can override this constant with a Web-specific implementation
const myMarshaler = IdentityMarshaler<MyDto>();

@SquadronService()
class MyService {
  @serviceMethod
  @myMarshaler
  FutureOr<MyDto> myMethod() {
    // ...
  }
}```

Why do you need to extend or implement it?

**Comment by d-markey** [comment]
> I have been doing this for a while but it's always been a bit annoying. I think this should be default behaviour unless user explicitly wants to use marshaler on VM as well.

Regarding this one, it would further complicate the code generation and I don't want to go down that path, it's already complicated enough to test and maintain. The only thing I can think of, is removing converters altogether if VM is the only target. For Web and VM+Web, converters are mandatory.
