### ISSUE TITLE
[v6.0.3][worker.g.dart] inspectRequest and response for generated worked code is true by default?

### ISSUE THREAD

**Issue by AlexDochioiu** [d-markey/squadron#44]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/8759be5e-00b6-4b49-b7f4-4790a0601101">
<img width="610" alt="image" src="https://github.com/user-attachments/assets/d993c5e7-9347-43c1-a1e0-49b7e1371ff9">

It seems that all my generated requests have inspect true despite the default being (in theory) false 🤔

**Comment by d-markey** [comment]
Fixed in 6.0.4.
