### ISSUE TITLE
[v6.0.3] False postive warnings?

### ISSUE THREAD

**Issue by AlexDochioiu** [d-markey/squadron#45]
I am getting tons of the below warnings since v6.

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/6d3bb370-7f22-4726-aee8-4d5a35f82cb6">

**Comment by d-markey** [comment]
I've seen these warnings but they originate from build_runner... also, I've noticed that these classes don't have any Squadron-related annotations (at least in my case), but they do have annotations from another package. I will investigate but it's a low priority. Shouldn't be an issue, just an annoying warning...

**Comment by d-markey** [comment]
Should be fixed in squadron_builder 6.0.5
