### ISSUE TITLE
`dartdoc` did not generate this page.

### ISSUE THREAD

**Issue by stephane-archer** [d-markey/squadron#48]
I can't learn to use the package, the documentation is not available

`dartdoc` did not generate this page.

https://pub.dev/documentation/squadron/latest/squadron_worker/Worker-class.html
https://pub.dev/documentation/squadron/latest/squadron_worker/WorkerPool-class.html

**Comment by d-markey** [comment]
Try these instead:

https://pub.dev/documentation/squadron/latest/squadron/Worker-class.html

https://pub.dev/documentation/squadron/latest/squadron/WorkerPool-class.html

But I don't recommend you use these classes manually. Use https://pub.dev/packages/squadron_builder instead, it will generate code for you.
