### ISSUE TITLE
Error during file import using Squadron in Flutter Web: "Unknown error"

### ISSUE THREAD

**Issue by gouthamrg** [d-markey/squadron#49]
I am encountering an issue while using the Squadron package in a Flutter Web application. When attempting to import and parse a file using a Squadron worker, I receive an "Unknown error" with the following stack trace:

`Error during file import: ["$sqdrn","Unknown error","dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 702:28              get current\npackages/squadron/src/exceptions/squadron_exception.dart 14:34                  init\npackages/squadron/src/exceptions/squadron_error.dart 8:62                       __\npackages/squadron/src/exceptions/squadron_error.dart 25:21                      SquadronErrorExt.create\npackages/squadron/src/_impl/web/_channel.dart 64:57                             $36errorHandler\ndart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 188:27  _callDartFunctionFast1\n"]`

Steps to Reproduce:

Create a service class with Squadron annotations to parse a file.
Generate the worker and worker pool code using build_runner.
Compile the worker code to JavaScript.
Use the generated worker in a Flutter Web application to parse a file.

Service Class:
```
import 'dart:async';
import 'package:squadron/squadron.dart';
import 'package:app/api/http/model/dtos/tsd_result_dto.dart';
import 'package:app/parser/tsd_parser.dart';

part 'tsd_parser_service.worker.g.dart';

@SquadronService(baseUrl: '~/workers', targetPlatform: TargetPlatform.vm | TargetPlatform.web)
class TsdParserService {
  @SquadronMethod()
  Future<TsdResultDto?> parseFile(String fileContent, String fileName) async {
    try {
      final tsdResultDto = TsdResultDto(
        id: 1,
        name: fileName,
        tsdData: await TsdParser.parseTsdFile(fileContent),
      );
      return tsdResultDto;
    } catch (e) {
      print("Error: $e");
      return null;
    }
  }
}
```

Worker Entry Point:

```
import 'package:squadron/squadron.dart';
import 'tsd_parser_service.dart';

void start(WorkerRequest request) => run((startRequest) => TsdParserService(), request);
```

Usage in Flutter Web Application:

```
Future<void> _importFile(BuildContext context) async {
    final localContext = context;

    setLoading(true); // Show loading spinner

    try {
      final FilePickResponse? file = await FilePickerService.pickFile();
      if (file == null) {
        print("No file selected.");
        return;
      }

      final String fileContent = file.content; // Ensure this is a raw string
      final String fileName = file.fileName;

      TsdResultDto? tsd;
      if (!kIsWeb) {
        tsd = await workerManager.execute(() async {
          return await TsdParser.parseFile(fileContent, fileName);
        }, priority: WorkPriority.immediately);
      } else {
        // use Squadron
        final worker = TsdParserServiceWorker();
        tsd = await worker.parseFile(fileContent, fileName);
      }

      if (tsd != null) {
        final TSDDataProvider tsdDataProvider =
            Provider.of<TSDDataProvider>(localContext, listen: false);
        tsdDataProvider.prepareVisualizerData(tsd);
      } else {
        print("Failed to parse the file.");
      }
    } catch (e) {
      print("Error during file import: $e");
    } finally {
      setLoading(false);
    }
  }
```

Additional Information:

Flutter version: 3.24v
Squadron version: 6.1.3
Squadron_builder: 6.1.1
Browser: Chrome

Expected Behavior: The file should be parsed successfully without any errors.

Actual Behavior: An "Unknown error" is encountered during file import.

Please let me know if you need any additional information or if there are any steps I might have missed. Thank you for your assistance!

**Comment by d-markey** [comment]
Hello,

This error is thrown very early in a worker's life cycle, actually it seems the worker cannot be instantiated.

Can you try this to check my assumption:

```dart
        // use Squadron
        final worker = TsdParserServiceWorker();
        await worker.start();
        // tsd = await worker.parseFile(fileContent, fileName);
        tsd = null;
```

I suspect this will fail on `await worker.start();`. Could you look at your browser's dev tool and check the network tab? You should see an HTTP request to load the `tsd_parser_service.dart.js`: is it successful with HTTP status code 200 or is there an error?

Also, you could try updating to the latest version of Squadron?

**Comment by d-markey** [comment]
Also, I would expect your service class to have another import in addition to `part 'tsd_parser_service.worker.g.dart'`:

```dart
import 'tsd_parser_service.activator.g.dart';
```

**Comment by gouthamrg** [comment]
Thanks for your Quick Response @d-markey .  Yes, you were right. When trying to load tsd_parser_service.web.g.dart.js, it throws 404 (not found).
![image](https://github.com/user-attachments/assets/3b54b2e1-c36d-464f-ac77-42d3b5d543f6)

I am trying to store the generated js file inside the build folder. 
This is the command I am using 

`dart compile js ".\lib\parser\tsd_parser_service.web.g.dart" -o ".\build\web\workers\tsd_parser_service.web.g.dart.js"`

**Comment by gouthamrg** [comment]
I have manged to fix the not found issue. My baseurl was wrong
I changed from 
`@SquadronService(baseUrl: '~/workers', targetPlatform: TargetPlatform.js)`
 to
 `@SquadronService(baseUrl: '~/build/web/workers', targetPlatform: TargetPlatform.js)`
  
  It worked. Thanks!.
  
@d-markey Great Package!! Amazing work :)

**Comment by d-markey** [comment]
> @d-markey Great Package!! Amazing work :)

And thank you btw :-)

**Comment by gouthamrg** [comment]
> It works in debug but might cause trouble when deploying to production.
> 
> Flutter runs your app from .\web in debug mode, so you should compile to .\web\workers (instead of .\build\web\workers) and keep the base URL as ~/workers.

Thanks for the info!
