### ISSUE TITLE
Using service fields in exposed methods

### ISSUE THREAD

**Issue by chip5441** [d-markey/squadron#50]
First of all, I appreciate you all guys for your time, efforts and resources spent to design and develop such a library.

This is not an issue but a feature which I would like to know without going through source code.

1. Consider an authentication service which has been annotated by squadron and consists of a single 'login' method which also annotated to be exposed. The concurrency settings provided for minimum 1 thread and maximum 3 threads. In 'login' method implementation, an object used which has been initialized before starting the thread pool. The object has been declared in service body. Is such object accessible in different worker threads by 'login' method?

2. Is it possible to use riverpod 'ref' in a service with minimum concurrency of 2 threads?

Thank you for an early reply.

**Comment by d-markey** [comment]
Hello,

if you hope to access some shared state across several workers, then the answer is no. Each worker has its own memory and Dart doesn't allow a worker to access another worker's memory. For instance in point one, there will be 1 to 3 different copies of your service class. Same goes for point two, you can use riverpod if you like but don't expect workers to be notified of changes happening in the main thread.

If you would like to learn more about Dart's concurrency model, here's an interesting read: https://dart.dev/language/concurrency

**Comment by d-markey** [comment]
> Hello,
> 
> if you hope to access some shared state across several workers, then the answer is no. Each worker has its own memory space and Dart doesn't allow a worker to access another worker's memory. For instance in point one, there will be 1 to 3 different copies of your service class. Same goes for point two, you can use riverpod if you like but don't expect workers to be notified of changes happening in the main thread.
> 
> If you would like to learn more about Dart's concurrency model, here's an interesting read: https://dart.dev/language/concurrency
