### ISSUE TITLE
Leader/Follower Pattern

### ISSUE THREAD

**Issue by chip5441** [d-markey/squadron#51]
Does 'squadron' use leader/follower pattern? If not then implementing such a pattern for concurrent processing, particularly mobile devices, could be great. Actually I was looking for a library similar to 'boost asio' concurrently model and fibers in dart. Found a few projects and at last decided to test 'squadron' to see if it is a good fit for first version of our product. Still playing with it. Also found discussions about threading support in dart which is still on going without any coding in action. FYI, our product backend is completely in 'C++' which is a service framework could be used as library or service on different platforms, locally and/or remotely. There are many features in our framework. Nevertheless, I would like to use 'squadron' in frontend development but I would like to make sure about least technical requirements I am looking for.
Thank you for your advice.

**Comment by d-markey** [comment]
Nope, Squadron is not about maintaining state across several workers.

Squadron aims at bringing a somewhat unified dev experience for multithreating across platforms, including the Web. Squadron implements the Actor pattern.
