### ISSUE TITLE
Feature Request: Immediate Worker/Isolate Shutdown and Call Cancellation

### ISSUE THREAD

**Issue by a-h-mzd** [d-markey/squadron#53]
I would like to request a new feature that allows us to immediately stop workers/isolates and cancel any in-progress calls. Currently, when we attempt to shut down a worker, it completes its ongoing tasks before actually exiting. This creates situations where we cannot quickly recover or free up resources, particularly in scenarios where graceful shutdowns are not desirable or feasible.

**Use Case:**
- Handling error states or timeouts where hanging processes need to be forcibly terminated.
- When a system or service needs to be quickly restarted or reconfigured.
- Improving system responsiveness and reliability by ensuring that stuck or long-running operations don’t hold up critical resources.

**Proposed Behavior:**
Introduce a method (e.g., forceStopWorkers() or shutdownImmediately()) that:
1. Terminates worker/isolates without waiting for ongoing calls to complete.
2. Cancels any currently executing calls, ensuring that no callbacks or promise resolutions occur after termination.
3. Returns a status or error code indicating that the termination was forced.

**Comment by a-h-mzd** [comment]
This functionality can easily be reproduced. 

**Steps to reproduce:**
1. Create an app with `hello world` example from the package.
2. Add a 4 second wait time before returning `'Hello, $name!'`
    <details>
    <summary><b>hello_world.dart</b></summary>
    
    ```dart
      @SquadronService(baseUrl: '~/workers', targetPlatform: TargetPlatform.all)
      base class HelloWorld {
        @SquadronMethod()
        FutureOr<String> hello([String? name]) async {
          await Future.delayed(const Duration(seconds: 4));
          name = name?.trim() ?? 'World';
          return 'Hello, $name!';
        }
      }
    ```
    </details>
3. Create a worker and call the hello function printing the result but stopping the working mid call.
    <details open>
    <summary><b>code</b></summary>
    
    ```dart
      final worker = HelloWorldWorker();
      Future.delayed(const Duration(seconds: 2), worker.stop);
      final message = await worker.hello();
      print(message);
    ```
    </details>
4. Observe that `worker.hello()` succeeds even though the worker was stopped.

**Comment by d-markey** [comment]
Hello,

This is something that can already be done via the PlatformThreadHook callback. With this callback, you can capture the thread (`Isolate` or Web `Worker`) so you can decide to kill it (`Isolate.kill()` or `Worker.terminate()`). You'll need a bit of conditional imports if you need both platforms but you can already manage it. You should stop the worker beforehand, to make sure Squadron knows the worker cannot be used anymore.

But it's an interesting feature request, I'll keep that in mind for a future release :-)

**Comment by d-markey** [comment]
Just one remark however, in the case of your example: I'm not quite sure what would happen... `final message = await worker.hello();` might never complete. So yes, probably better to wait for a proper implementation in Squadron.

**Comment by d-markey** [comment]
You can upgrade to 6.1.4 and try this:

```dart
  final worker = HelloWorldWorker();
  Future.delayed(const Duration(seconds: 2), worker.terminate);
  final message = await worker.hello();
  print(message);
```

`terminate()` is provided by `IWorker`, so it's also available on worker pools.

**Comment by d-markey** [comment]
Any feedback? Is it doing what you expected?

**Comment by a-h-mzd** [comment]
@d-markey, thank you for looking into this. I tried to check the new version, but `squadron_builder` seems to have a problem with the latest `analyzer` versions.

<details>
<summary><b>Build output</b></summary>

``` console
[INFO] Generating build script...
[INFO] Generating build script completed, took 167ms

[INFO] Precompiling build script......
[WARNING] ../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/worker_builder.dart:42:23: Error: The argument type 'String Function(String, Version)' can't be assigned to the parameter type 'String Function(String)?'.
 - 'Version' is from 'package:pub_semver/src/version.dart' ('../../.pub-cache/hosted/pub.dev/pub_semver-2.1.5/lib/src/version.dart').
        formatOutput: formatOutput,
                      ^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/type_manager.dart:57:20: Error: The getter 'prefixes' isn't defined for the class 'LibraryElement'.
 - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'prefixes'.
    return library.prefixes
                   ^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/marshaler_inspector.dart:35:46: Error: The getter 'accessibleExtensions' isn't defined for the class 'LibraryElement'.
 - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accessibleExtensions'.
      final extensions = typeManager.library.accessibleExtensions
                                             ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/marshaler_inspector.dart:50:25: Error: The getter 'enclosingElement' isn't defined for the class 'Element'.
 - 'Element' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement'.
          ? _unmarshal!.enclosingElement!
                        ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/marshaler_inspector.dart:51:34: Error: The getter 'enclosingElement' isn't defined for the class 'Element'.
 - 'Element' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement'.
          : (isJson ? _fromJson!.enclosingElement! : null);
                                 ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/extensions.dart:42:7: Error: The getter 'libraryImports' isn't defined for the class 'LibraryElement'.
 - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'libraryImports'.
      libraryImports.where((i) => i.isFromPackage(pckUri)).firstOrNull;
      ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/types/extensions.dart:46:9: Error: The getter 'libraryImports' isn't defined for the class 'LibraryElement'.
 - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'libraryImports'.
        libraryImports.where((i) => i.isFromPackage(pckUri)).firstOrNull;
        ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/marshalers/marshaler_explicit.dart:21:20: Error: The getter 'enclosingElement' isn't defined for the class 'VariableElement'.
 - 'VariableElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement'.
      if (variable.enclosingElement is InterfaceElement) {
                   ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/marshalers/marshaler_explicit.dart:22:33: Error: The getter 'enclosingElement' isn't defined for the class 'VariableElement'.
 - 'VariableElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement'.
        _instance = '${variable.enclosingElement!.name!}.${variable.name}';
                                ^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/squadron_builder-6.1.4/lib/src/readers/squadron_method_reader.dart:67:23: Error: The getter 'enclosingElement' isn't defined for the class 'MethodElement'.
 - 'MethodElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dev/analyzer-7.1.0/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'enclosingElement'.
          '\'${method.enclosingElement.displayName}.${method.name}\' must '
                      ^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 677ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

Failed to update packages.
```
</details>

**Comment by d-markey** [comment]
Could you pin squadron_builder version to 6.1.2? I'm going to retract the versions I just published.

**Comment by a-h-mzd** [comment]
It sure now throws instead of returning the results but the problem with this approach is that the task is still ongoing and the running thread/service_worker is still consuming resources. The terminate command should kill the spawned worker and free all the resources immediately.

**Comment by a-h-mzd** [comment]
Check the code below 👇🏼 
```dart
import 'dart:isolate';

Future<String> test() async {
  await Future.delayed(Duration(seconds: 4));
  return 'Hello World!';
}

Future<void> main() async {
  final receivePort = ReceivePort();
  final isolate = await Isolate.spawn(
    isolateFunction,
    receivePort.sendPort,
    errorsAreFatal: true,
    onExit: receivePort.sendPort,
  );

  // comment this line to see the result
  Future.delayed(Duration(seconds: 2), isolate.kill);

  final result = await receivePort.first;
  if (result == null) {
    throw Exception('Isolate terminated before sending a response');
  }
  print(result);
}

Future<void> isolateFunction(SendPort sendPort) async {
  final result = await test();
  sendPort.send(result);
}
```

**Comment by d-markey** [comment]
Your example is using the same port to send the method result and the termination message, which is not how Squadron is designed. Squadron is designed to implement your service interface in a worker class, and service methods typically return `Future<T>` or `Stream<T>` (possibly nullable, but also possibly void or not nullable). So `null` cannot be used as a "marker" that the worker has been terminated. This would be a breach of contract, and would also break type-safety. Instead, you have to implement proper error handling to handle termination situations.

In terms of ressources, `terminate()` on VM calls `Isolate.kill()` so I believe resources are freed. Why do you say they're not?

I've implemented a sample in https://github.com/d-markey/squadron/blob/main/example/streaming/terminate.dart. This example is based on a streaming method that emits a number every X milliseconds. The stream is infinite (`while (true)`) and the subscription is never cancelled in user code. When `terminate()` is called, I can verify that the streaming operation is stopped as well as the worker.

Example output:

`$ dart run .\example\streaming\terminate.dart`

```
[0x30685471] [0:00:00.027334] Starting clock
[0x2ed1ae24] Sending  1 from service
[0x30685471] [0:00:00.043718] Received 1 from worker
[0x2ed1ae24] Sending  2 from service
[0x30685471] [0:00:00.559503] Received 2 from worker
[0x30685471] [0:00:01.043946] Clock status: running, up time = 0:00:01.019683, current workload = 1, total workload = 0
[0x2ed1ae24] Sending  3 from service
[0x30685471] [0:00:01.061141] Received 3 from worker
[0x2ed1ae24] Sending  4 from service
[0x30685471] [0:00:01.564059] Received 4 from worker
[0x30685471] [0:00:02.051031] Clock status: running, up time = 0:00:02.028042, current workload = 1, total workload = 0
[0x2ed1ae24] Sending  5 from service
[0x30685471] [0:00:02.066977] Received 5 from worker
[0x2ed1ae24] Sending  6 from service
[0x30685471] [0:00:02.583818] Received 6 from worker
[0x30685471] [0:00:03.046556] Killing worker
[0x30685471] [0:00:03.066988] Received error ["$K","Worker has been killed",null]
[0x30685471] [0:00:03.069200] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x2ed1ae24] Sending  7 from service
[0x30685471] [0:00:04.050279] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:05.054176] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:06.042711] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:07.052037] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:08.043002] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:09.048343] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:10.055099] Clock status: stopped, up time = 0:00:03.023372, current workload = 0, total workload = 1
[0x30685471] [0:00:10.055782] Terminating program
```

**Comment by a-h-mzd** [comment]
The example I provided was just an illustration of how to achieve isolate termination, which is the point of this feature request. For the part where null is returned, we can easily define a response class and associate null with isolate termination.

**Comment by a-h-mzd** [comment]
To check if the isolate/worker is terminated, you can verify whether the function provided to the isolate continues to execute or is terminated the moment the isolate termination command is called, with the latter being the expected result. To do this, you can make the function passed to the isolate wait for 6 seconds before returning the result. Then, terminate the isolate after 1 second, and the function call should throw immediately instead of waiting for the function to complete execution before throwing.

**Comment by d-markey** [comment]
Hello, you were right, termination was not effective immediately. I implemented it at a lower level and it should now work properly. See examples in `example/worker` and `example/streamingv (files `termination.dart`)

**Comment by a-h-mzd** [comment]
The newest version(6.1.6) is working as expected now. I didn't have the time to check it on the web(yet), but on io it looks perfect. 🚀

**Comment by a-h-mzd** [comment]
![image](https://github.com/user-attachments/assets/16cb86ce-1096-4c61-854f-b063a0ab807f)
